### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by xorJane** [JuliaAcademy/JuliaTutorials#14]
The licensing issue identified to us by Software Carpentry is the Licensing.md file in this directory, which has a statement about copyright. Can we simply remove this material, or should we replace it with other licensing info making it clear this material is meant to be free and open? @ViralBShah @DeepakVinchhi

**Comment by ViralBShah** [comment]
Do they want to adopt our materials and build further on that?

Let's figure this out next week. We need to be careful about the 500k or other materials we are not ready to put out. But if this is stuff from the youtube tutorials, we can make it all MIT licensed.

**Comment by ViralBShah** [comment]
@xorJane Please do stay on top of this and get it sorted out.

**Comment by aviks** [comment]
I'd talked about this on Slack a few days ago, but I don't think I made myself very clear. So thanks for raising this, Jane. 

@ViralBShah this repo does not contain any 500K material, so that is not an issue. 

Jane, we need to to license each directory, since this contains materials by different author. All JC authored material should be made MIT. Could you please: 

* Raise a PR to remove the current license file, and add an MIT license file to the directories created by JC employees:  viz "Intro to Julia", "intro -es", "metaprogramning", "parallellism" and "juliadb" 

For the others, we need to get explicit licenses from the original authors. this can be by e-mail, or as a PR to this repo that they explicitly approve. the latter might be cleaner, as it provides an audit trail.

**Comment by xorJane** [comment]
Hey Avik, sounds great. Will do!

Re. Intro to Julia ES, those materials were translated by Miguel Raz but based on my notebooks. How do we split licensing in cases like that?

**Comment by aviks** [comment]
In general, derivative works will have to follow the rules of the original licence. Since the MIT is very flexible, we should probably then ask Miguel what he wants. If he is OK with MIT, that's easy. If he wants something else, the original MIT license will also have to be placed in that repo.

**Comment by ViralBShah** [comment]
I would add Miguel as the copyright owner there. I think he will be ok.

**Comment by logankilpatrick** [comment]
https://github.com/JuliaAcademy/JuliaTutorials/blob/main/LICENSE.md
